//
// SynthInC
//
// Created by Brad Howes
// Copyright (c) 2016 Brad Howes. All rights reserved.

let GeneralUserGSMuseScoreversion1442SoundFont = SoundFont("GeneralUser GS MuseScore version 1.442", fileName: "GeneralUser GS MuseScore v1.442", [
    Patch("Stereo Grand",                  0,   0),
    Patch("Bright Grand",                  0,   1),
    Patch("Electric Grand",                0,   2),
    Patch("Honky-Tonk",                    0,   3),
    Patch("Tine Electric Piano",           0,   4),
    Patch("FM Electric Piano",             0,   5),
    Patch("Harpsichord",                   0,   6),
    Patch("Clavinet",                      0,   7),
    Patch("Celeste",                       0,   8),
    Patch("Glockenspiel",                  0,   9),
    Patch("Music Box",                     0,  10),
    Patch("Vibraphone",                    0,  11),
    Patch("Marimba",                       0,  12),
    Patch("Xylophone",                     0,  13),
    Patch("Tubular Bells",                 0,  14),
    Patch("Dulcimer",                      0,  15),
    Patch("Tonewheel Organ",               0,  16),
    Patch("Percussive Organ",              0,  17),
    Patch("Rock Organ",                    0,  18),
    Patch("Pipe Organ",                    0,  19),
    Patch("Reed Organ",                    0,  20),
    Patch("Accordian",                     0,  21),
    Patch("Harmonica",                     0,  22),
    Patch("Bandoneon",                     0,  23),
    Patch("Nylon Guitar",                  0,  24),
    Patch("Steel Guitar",                  0,  25),
    Patch("Jazz Guitar",                   0,  26),
    Patch("Clean Guitar",                  0,  27),
    Patch("Muted Guitar",                  0,  28),
    Patch("Overdrive Guitar",              0,  29),
    Patch("Distortion Guitar",             0,  30),
    Patch("Guitar Harmonics",              0,  31),
    Patch("Acoustic Bass",                 0,  32),
    Patch("Finger Bass",                   0,  33),
    Patch("Pick Bass",                     0,  34),
    Patch("Fretless Bass",                 0,  35),
    Patch("Slap Bass 1",                   0,  36),
    Patch("Slap Bass 2",                   0,  37),
    Patch("Synth Bass 1",                  0,  38),
    Patch("Synth Bass 2",                  0,  39),
    Patch("Violin",                        0,  40),
    Patch("Viola",                         0,  41),
    Patch("Cello",                         0,  42),
    Patch("Double Bass",                   0,  43),
    Patch("Stereo Strings Trem",           0,  44),
    Patch("Pizzicato Strings",             0,  45),
    Patch("Orchestral Harp",               0,  46),
    Patch("Timpani",                       0,  47),
    Patch("Stereo Strings Fast",           0,  48),
    Patch("Stereo Strings Slow",           0,  49),
    Patch("Synth Strings 1",               0,  50),
    Patch("Synth Strings 2",               0,  51),
    Patch("Concert Choir",                 0,  52),
    Patch("Voice Oohs",                    0,  53),
    Patch("Synth Voice",                   0,  54),
    Patch("Orchestra Hit",                 0,  55),
    Patch("Trumpet",                       0,  56),
    Patch("Trombone",                      0,  57),
    Patch("Tuba",                          0,  58),
    Patch("Muted Trumpet",                 0,  59),
    Patch("French Horns",                  0,  60),
    Patch("Brass Section",                 0,  61),
    Patch("Synth Brass 1",                 0,  62),
    Patch("Synth Brass 2",                 0,  63),
    Patch("Soprano Sax",                   0,  64),
    Patch("Alto Sax",                      0,  65),
    Patch("Tenor Sax",                     0,  66),
    Patch("Baritone Sax",                  0,  67),
    Patch("Oboe",                          0,  68),
    Patch("English Horn",                  0,  69),
    Patch("Bassoon",                       0,  70),
    Patch("Clarinet",                      0,  71),
    Patch("Piccolo",                       0,  72),
    Patch("Flute",                         0,  73),
    Patch("Recorder",                      0,  74),
    Patch("Pan Flute",                     0,  75),
    Patch("Bottle Blow",                   0,  76),
    Patch("Shakuhachi",                    0,  77),
    Patch("Irish Tin Whistle",             0,  78),
    Patch("Ocarina",                       0,  79),
    Patch("Square Lead",                   0,  80),
    Patch("Saw Lead",                      0,  81),
    Patch("Synth Calliope",                0,  82),
    Patch("Chiffer Lead",                  0,  83),
    Patch("Charang",                       0,  84),
    Patch("Solo Vox",                      0,  85),
    Patch("5th Saw Wave",                  0,  86),
    Patch("Bass & Lead",                   0,  87),
    Patch("Fantasia",                      0,  88),
    Patch("Warm Pad",                      0,  89),
    Patch("Polysynth",                     0,  90),
    Patch("Space Voice",                   0,  91),
    Patch("Bowed Glass",                   0,  92),
    Patch("Metal Pad",                     0,  93),
    Patch("Halo Pad",                      0,  94),
    Patch("Sweep Pad",                     0,  95),
    Patch("Ice Rain",                      0,  96),
    Patch("Soundtrack",                    0,  97),
    Patch("Crystal",                       0,  98),
    Patch("Atmosphere",                    0,  99),
    Patch("Brightness",                    0, 100),
    Patch("Goblin",                        0, 101),
    Patch("Echo Drops",                    0, 102),
    Patch("Star Theme",                    0, 103),
    Patch("Sitar",                         0, 104),
    Patch("Banjo",                         0, 105),
    Patch("Shamisen",                      0, 106),
    Patch("Koto",                          0, 107),
    Patch("Kalimba",                       0, 108),
    Patch("Bagpipes",                      0, 109),
    Patch("Fiddle",                        0, 110),
    Patch("Shenai",                        0, 111),
    Patch("Tinker Bell",                   0, 112),
    Patch("Agogo",                         0, 113),
    Patch("Steel Drums",                   0, 114),
    Patch("Wood Block",                    0, 115),
    Patch("Taiko Drum",                    0, 116),
    Patch("Melodic Tom",                   0, 117),
    Patch("Synth Drum",                    0, 118),
    Patch("Reverse Cymbal",                0, 119),
    Patch("Fret Noise",                    0, 120),
    Patch("Breath Noise",                  0, 121),
    Patch("Seashore",                      0, 122),
    Patch("Birds",                         0, 123),
    Patch("Telephone 1",                   0, 124),
    Patch("Helicopter",                    0, 125),
    Patch("Applause",                      0, 126),
    Patch("Gun Shot",                      0, 127),
    Patch("Synth Bass 101",                1,  38),
    Patch("Mono Strings Trem",             1,  44),
    Patch("Mono Strings Fast",             1,  48),
    Patch("Mono Strings Slow",             1,  49),
    Patch("Concert Choir Mono",            1,  52),
    Patch("Trumpet 2",                     1,  56),
    Patch("Trombone 2",                    1,  57),
    Patch("Muted Trumpet 2",               1,  59),
    Patch("Solo French Horn",              1,  60),
    Patch("Brass Section Mono",            1,  61),
    Patch("Square Wave",                   1,  80),
    Patch("Saw Wave",                      1,  81),
    Patch("Synth Mallet",                  1,  98),
    Patch("Cut Noise",                     1, 120),
    Patch("Fl. Key Click",                 1, 121),
    Patch("Rain",                          1, 122),
    Patch("Dog",                           1, 123),
    Patch("Telephone 2",                   1, 124),
    Patch("Car-Engine",                    1, 125),
    Patch("Laughing",                      1, 126),
    Patch("Machine Gun",                   1, 127),
    Patch("Echo Pan",                      2, 102),
    Patch("String Slap",                   2, 120),
    Patch("Thunder",                       2, 122),
    Patch("Horse Gallop",                  2, 123),
    Patch("Door Creaking",                 2, 124),
    Patch("Car-Stop",                      2, 125),
    Patch("Scream",                        2, 126),
    Patch("Lasergun",                      2, 127),
    Patch("Howling Winds",                 3, 122),
    Patch("Bird 2",                        3, 123),
    Patch("Door",                          3, 124),
    Patch("Car-Pass",                      3, 125),
    Patch("Punch",                         3, 126),
    Patch("Explosion",                     3, 127),
    Patch("Stream",                        4, 122),
    Patch("Scratch",                       4, 123),
    Patch("Car-Crash",                     4, 125),
    Patch("Heart Beat",                    4, 126),
    Patch("Bubbles",                       5, 122),
    Patch("Windchime",                     5, 124),
    Patch("Siren",                         5, 125),
    Patch("Footsteps",                     5, 126),
    Patch("Train",                         6, 125),
    Patch("Jet Plane",                     7, 125),
    Patch("Chorused Tine EP",              8,   4),
    Patch("Chorused FM EP",                8,   5),
    Patch("Coupled Harpsichord",           8,   6),
    Patch("Church Bells",                  8,  14),
    Patch("Detuned Tnwl. Organ",           8,  16),
    Patch("Detuned Perc. Organ",           8,  17),
    Patch("Pipe Organ 2",                  8,  19),
    Patch("Italian Accordian",             8,  21),
    Patch("Ukulele",                       8,  24),
    Patch("12-String Guitar",              8,  25),
    Patch("Hawaiian Guitar",               8,  26),
    Patch("Chorused Clean Gt.",            8,  27),
    Patch("Funk Guitar",                   8,  28),
    Patch("Feedback Guitar",               8,  30),
    Patch("Guitar Feedback",               8,  31),
    Patch("Synth Bass 3",                  8,  38),
    Patch("Synth Bass 4",                  8,  39),
    Patch("Orchestra Pad",                 8,  48),
    Patch("Synth Strings 3",               8,  50),
    Patch("Brass Section 2",               8,  61),
    Patch("Synth Brass 3",                 8,  62),
    Patch("Synth Brass 4",                 8,  63),
    Patch("Sine Wave",                     8,  80),
    Patch("Doctor Solo",                   8,  81),
    Patch("Taisho Koto",                   8, 107),
    Patch("Castanets",                     8, 115),
    Patch("Concert Bass Drum",             8, 116),
    Patch("Melodic Tom 2",                 8, 117),
    Patch("808 Tom",                       8, 118),
    Patch("Starship",                      8, 125),
    Patch("Carillon",                      9,  14),
    Patch("Burst Noise",                   9, 125),
    Patch("Piano & Str.-Fade",            11,   0),
    Patch("Piano & Str.-Sus",             11,   1),
    Patch("Tine & FM EPs",                11,   4),
    Patch("Piano & FM EP",                11,   5),
    Patch("Tinkling Bells",               11,   8),
    Patch("Bell Tower",                   11,  14),
    Patch("Techno Bass",                  11,  38),
    Patch("Pulse Bass",                   11,  39),
    Patch("Stereo Strings Velo",          11,  49),
    Patch("Synth Strings 4",              11,  50),
    Patch("Synth Strings 5",              11,  51),
    Patch("Brass Section 3",              11,  61),
    Patch("Whistlin'",                    11,  78),
    Patch("Sawtooth Stab",                11,  81),
    Patch("Doctor's Solo",                11,  87),
    Patch("Harpsi Pad",                   11,  88),
    Patch("Solar Wind",                   11,  89),
    Patch("Mystery Pad",                  11,  96),
    Patch("Synth Chime",                  11,  98),
    Patch("Bright Saw Stack",             11, 100),
    Patch("Cymbal Crash",                 11, 119),
    Patch("Filter Snap",                  11, 121),
    Patch("Interference",                 11, 127),
    Patch("Bell Piano",                   12,   0),
    Patch("Bell Tine EP",                 12,   4),
    Patch("Christmas Bells",              12,  10),
    Patch("Clean Guitar 2",               12,  27),
    Patch("Mean Saw Bass",                12,  38),
    Patch("Full Orchestra",               12,  48),
    Patch("Mono Strings Velo",            12,  49),
    Patch("Square Lead 2",                12,  80),
    Patch("Saw Lead 2",                   12,  81),
    Patch("Fantasia 2",                   12,  88),
    Patch("Solar Wind 2",                 12,  89),
    Patch("Tambourine",                   12, 119),
    Patch("White Noise Wave",             12, 122),
    Patch("Shooting Star",                12, 127),
    Patch("Woodwind Choir",               13,  48),
    Patch("Square Lead 3",                13,  80),
    Patch("Saw Lead 3",                   13,  81),
    Patch("Night Vision",                 13,  88),
    Patch("Mandolin",                     16,  25),
    Patch("Standard Drums",              120,   0),
    Patch("Standard 2 Drums",            120,   1),
    Patch("Room Drums",                  120,   8),
    Patch("Power Drums",                 120,  16),
    Patch("Electronic Drums",            120,  24),
    Patch("808/909 Drums",               120,  25),
    Patch("Dance Drums",                 120,  26),
    Patch("Jazz Drums",                  120,  32),
    Patch("Brush Drums",                 120,  40),
    Patch("Orchestral Perc.",            120,  48),
    Patch("SFX Kit",                     120,  56),
    Patch("Standard+Orch",               128,   0),
    Patch("Standard 2",                  128,   1),
    Patch("Standard 3",                  128,   2),
    Patch("Room",                        128,   8),
    Patch("Power",                       128,  16),
    Patch("Electronic",                  128,  24),
    Patch("808/909",                     128,  25),
    Patch("Dance",                       128,  26),
    Patch("Jazz",                        128,  32),
    Patch("Brush",                       128,  40),
    Patch("Orchestral",                  128,  48),
    Patch("SFX",                         128,  56),
])
