//
//  GeneralUser.swift
//  SynthInC
//
//  Created by Brad Howes on 6/8/16.
//  Copyright © 2016 Brad Howes. All rights reserved.
//

import Foundation

/// Definition of the GeneralUser GS MuseScore sound font
let GeneralUserSoundFont = SoundFont("GeneralUser", fileName: "GeneralUser GS MuseScore v1.442", [
    Patch("Acoustic Grand Piano", 0, 0),
    Patch("Bright Acoustic Piano", 0, 1),
    Patch("Electric Grand Piano", 0, 2),
    Patch("Honky-tonk Piano", 0, 3),
    Patch("Electric Piano 1", 0, 4),
    Patch("Electric Piano 2", 0, 5),
    Patch("Harpsichord", 0, 6),
    Patch("Clavi", 0, 7),
    Patch("Celesta", 0, 8),
    Patch("Glockenspiel", 0, 9),
    Patch("Music Box", 0, 10),
    Patch("Vibraphone", 0, 11),
    Patch("Marimba", 0, 12),
    Patch("Xylophone", 0, 13),
    Patch("Tubular Bells", 0, 14),
    Patch("Dulcimer", 0, 15),
    Patch("Drawbar Organ", 0, 16),
    Patch("Percussive Organ", 0, 17),
    Patch("Rock Organ", 0, 18),
    Patch("ChurchPipe", 0, 19),
    Patch("Positive", 0, 20),
    Patch("Accordion", 0, 21),
    Patch("Harmonica", 0, 22),
    Patch("Tango Accordion", 0, 23),
    Patch("Classic Guitar", 0, 24),
    Patch("Acoustic Guitar", 0, 25),
    Patch("Jazz Guitar", 0, 26),
    Patch("Clean Guitar", 0, 27),
    Patch("Muted Guitar", 0, 28),
    Patch("Overdriven Guitar", 0, 29),
    Patch("Distortion Guitar", 0, 30),
    Patch("Guitar harmonics", 0, 31),
    Patch("JazzBass", 0, 32),
    Patch("DeepBass", 0, 33),
    Patch("PickBass", 0, 34),
    Patch("FretLess", 0, 35),
    Patch("SlapBass1", 0, 36),
    Patch("SlapBass2", 0, 37),
    Patch("SynthBass1", 0, 38),
    Patch("SynthBass2", 0, 39),
    Patch("Violin", 0, 40),
    Patch("Viola", 0, 41),
    Patch("Cello", 0, 42),
    Patch("ContraBass", 0, 43),
    Patch("TremoloStr", 0, 44),
    Patch("Pizzicato", 0, 45),
    Patch("Harp", 0, 46),
    Patch("Timpani", 0, 47),
    Patch("String Ensemble 1", 0, 48),
    Patch("String Ensemble 2", 0, 49),
    Patch("SynthStrings 1", 0, 50),
    Patch("SynthStrings 2", 0, 51),
    Patch("Choir", 0, 52),
    Patch("DooVoice", 0, 53),
    Patch("Voices", 0, 54),
    Patch("OrchHit", 0, 55),
    Patch("Trumpet", 0, 56),
    Patch("Trombone", 0, 57),
    Patch("Tuba", 0, 58),
    Patch("MutedTrumpet", 0, 59),
    Patch("FrenchHorn", 0, 60),
    Patch("Brass", 0, 61),
    Patch("SynBrass1", 0, 62),
    Patch("SynBrass2", 0, 63),
    Patch("SopranoSax", 0, 64),
    Patch("AltoSax", 0, 65),
    Patch("TenorSax", 0, 66),
    Patch("BariSax", 0, 67),
    Patch("Oboe", 0, 68),
    Patch("EnglishHorn", 0, 69),
    Patch("Bassoon", 0, 70),
    Patch("Clarinet", 0, 71),
    Patch("Piccolo", 0, 72),
    Patch("Flute", 0, 73),
    Patch("Recorder", 0, 74),
    Patch("PanFlute", 0, 75),
    Patch("Bottle", 0, 76),
    Patch("Shakuhachi", 0, 77),
    Patch("Whistle", 0, 78),
    Patch("Ocarina", 0, 79),
    Patch("SquareWave", 0, 80),
    Patch("SawWave", 0, 81),
    Patch("Calliope", 0, 82),
    Patch("SynChiff", 0, 83),
    Patch("Charang", 0, 84),
    Patch("AirChorus", 0, 85),
    Patch("fifths", 0, 86),
    Patch("BassLead", 0, 87),
    Patch("New Age", 0, 88),
    Patch("WarmPad", 0, 89),
    Patch("PolyPad", 0, 90),
    Patch("GhostPad", 0, 91),
    Patch("BowedGlas", 0, 92),
    Patch("MetalPad", 0, 93),
    Patch("HaloPad", 0, 94),
    Patch("Sweep", 0, 95),
    Patch("IceRain", 0, 96),
    Patch("SoundTrack", 0, 97),
    Patch("Crystal", 0, 98),
    Patch("Atmosphere", 0, 99),
    Patch("Brightness", 0, 100),
    Patch("Goblin", 0, 101),
    Patch("EchoDrop", 0, 102),
    Patch("SciFi effect", 0, 103),
    Patch("Sitar", 0, 104),
    Patch("Banjo", 0, 105),
    Patch("Shamisen", 0, 106),
    Patch("Koto", 0, 107),
    Patch("Kalimba", 0, 108),
    Patch("Scotland", 0, 109),
    Patch("Fiddle", 0, 110),
    Patch("Shanai", 0, 111),
    Patch("MetalBell", 0, 112),
    Patch("Agogo", 0, 113),
    Patch("SteelDrums", 0, 114),
    Patch("Woodblock", 0, 115),
    Patch("Taiko", 0, 116),
    Patch("Tom", 0, 117),
    Patch("SynthTom", 0, 118),
    Patch("RevCymbal", 0, 119),
    Patch("FretNoise", 0, 120),
    Patch("NoiseChiff", 0, 121),
    Patch("Seashore", 0, 122),
    Patch("Birds", 0, 123),
    Patch("Telephone", 0, 124),
    Patch("Helicopter", 0, 125),
    Patch("Stadium", 0, 126),
    Patch("GunShot", 0, 127)
    ])

